# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55ec9f6e411723aa5a9fc635e21b27ccb311ac0bf629a69ef1b5a28c86bd9b47c0fa8054123191025a41252ee9b27d69e2b3b8adda59db4fae8caa00a1d07b6c

test:
  secret_key_base: a18dd50b60e3696b08fa9cd994b4eb17d6dc35e19c7b7b9b6bf2f98e92d9c023e546dd3cc9a3d38a1e82f918111d5f2b458f114b059c831aeb9462e7272f6467

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
